name: SRP
channels:
  - conda-forge
  - defaults
dependencies:
  - _python_abi3_support=1.0
  - absl-py=2.3.1
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.12.15
  - aiosignal=1.4.0
  - appnope=0.1.4
  - asttokens=3.0.0
  - astunparse=1.6.3
  - attrs=25.3.0
  - biotraj=1.2.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.10.5
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.4
  - certifi=2025.10.5
  - cffi=2.0.0
  - charset-normalizer=3.4.3
  - colorama=0.4.6
  - comm=0.2.3
  - contourpy=1.3.3
  - cpython=3.12.11
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - debugpy=1.8.17
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - fair-esm=2.0.0
  - filelock=3.19.1
  - flatbuffers=24.12.23
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.60.1
  - freetype=2.14.1
  - freetype-py=2.3.0
  - frozenlist=1.7.0
  - fsspec=2025.9.0
  - gast=0.6.0
  - gemmi=0.7.3
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - google-pasta=0.2.0
  - greenlet=3.2.4
  - grpcio=1.67.1
  - h2=4.3.0
  - h5py=3.14.0
  - hdf5=1.14.6
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.7.0
  - ipykernel=6.30.1
  - ipython=9.6.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jinja2=3.1.6
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - keras=3.11.2
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20240722.0
  - libaec=1.1.4
  - libblas=3.9.0
  - libboost=1.86.0
  - libboost-python=1.86.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcurl=8.14.1
  - libcxx=21.1.2
  - libdeflate=1.24
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.1
  - libffi=3.4.6
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libglib=2.86.0
  - libgrpc=1.67.1
  - libiconv=1.18
  - libintl=0.25.1
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libml_dtypes-headers=0.5.3
  - libnghttp2=1.67.0
  - libntlm=1.8
  - libopenblas=0.3.30
  - libpng=1.6.50
  - libpq=18.0
  - libprotobuf=5.28.3
  - librdkit=2025.09.1
  - libre2-11=2024.07.02
  - libsodium=1.0.20
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libtensorflow_cc=2.18.0
  - libtensorflow_framework=2.18.0
  - libtiff=4.7.1
  - libtorch=2.6.0
  - libuv=1.51.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libxslt=1.1.43
  - libzlib=1.3.1
  - llvm-openmp=21.1.2
  - lxml=6.0.2
  - markdown=3.9
  - markdown-it-py=4.0.0
  - markupsafe=3.0.3
  - matplotlib-base=3.10.6
  - matplotlib-inline=0.1.7
  - mdurl=0.1.2
  - ml_dtypes=0.4.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - msgpack-python=1.1.2
  - multidict=6.6.3
  - munkres=1.1.4
  - namex=0.1.0
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.5
  - nomkl=1.0
  - openjpeg=2.5.4
  - openldap=2.6.10
  - openssl=3.5.4
  - opt_einsum=3.4.0
  - optree=0.17.0
  - packaging=25.0
  - pandas=2.3.3
  - parso=0.8.5
  - pcre2=10.46
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - platformdirs=4.5.0
  - prompt-toolkit=3.0.52
  - propcache=0.3.1
  - protobuf=5.28.3
  - psutil=7.1.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pybind11=3.0.1
  - pybind11-global=3.0.1
  - pycairo=1.28.0
  - pycparser=2.22
  - pygments=2.19.2
  - pyparsing=3.2.5
  - pysocks=1.7.1
  - python=3.12.11
  - python-dateutil=2.9.0.post0
  - python-flatbuffers=25.9.23
  - python-gil=3.12.11
  - python-tzdata=2025.2
  - python_abi=3.12
  - pytorch=2.6.0
  - pytorch_geometric=2.6.1
  - pytz=2025.2
  - pyzmq=27.1.0
  - qhull=2020.2
  - rdkit=2025.09.1
  - re2=2024.07.02
  - readline=8.2
  - reportlab=4.4.4
  - requests=2.32.5
  - rich=14.1.0
  - rlpycairo=0.4.0
  - scipy=1.16.2
  - setuptools=80.9.0
  - six=1.17.0
  - sleef=3.9.0
  - snappy=1.2.2
  - sqlalchemy=2.0.43
  - stack_data=0.6.3
  - sympy=1.14.0
  - tensorboard=2.18.0
  - tensorboard-data-server=0.7.0
  - tensorflow=2.18.0
  - tensorflow-base=2.18.0
  - tensorflow-estimator=2.18.0
  - termcolor=3.1.0
  - tk=8.6.13
  - torch-scatter=2.1.1
  - tornado=6.5.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - unicodedata2=16.0.0
  - urllib3=2.5.0
  - wcwidth=0.2.14
  - werkzeug=3.1.3
  - wheel=0.45.1
  - wrapt=1.17.3
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - yarl=1.20.1
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib-ng=2.2.5
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - addict==2.4.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.11.0
      - click==8.3.0
      - einops==0.8.1
      - h11==0.16.0
      - hatch-cython==0.5.1
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.0.1
      - hydra-core==1.3.2
      - joblib==1.5.2
      - llvmlite==0.45.1
      - lmdb==1.7.5
      - numba==0.62.1
      - numpy==2.2.6
      - omegaconf==2.3.0
      - pyyaml==6.0.3
      - scikit-learn==1.7.2
      - shellingham==1.5.4
      - sniffio==1.3.1
      - threadpoolctl==3.6.0
      - typer-slim==0.20.0
      - unimol-tools==0.1.5
      - yacs==0.1.8
prefix: /opt/miniconda3/envs/SRP
